/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Patient {
    age: bigint;
    exerciseInducedAngina: boolean;
    maxHeartRate: bigint;
    chestPain: ChestPainType;
    majorVessels: bigint;
    race: Race;
    thal: Thalassemia;
    restingBP: bigint;
    slope: bigint;
    gender: Gender;
    stDepression: number;
    heartDisease: boolean;
    strokeHistory: boolean;
    diabetes: boolean;
    fastingBloodSugar: boolean;
    restingECG: bigint;
    cholesterol: bigint;
}
export enum ChestPainType {
    atypicalAngina = "atypicalAngina",
    typicalAngina = "typicalAngina",
    asymptomatic = "asymptomatic",
    nonAnginalPain = "nonAnginalPain"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Race {
    asian = "asian",
    other = "other",
    latino = "latino",
    black = "black",
    white = "white"
}
export enum Thalassemia {
    normal = "normal",
    fixedDefect = "fixedDefect",
    reversibleDefect = "reversibleDefect"
}
export interface backendInterface {
    getConfiguration(): Promise<{
        ageMax: bigint;
        ageMin: bigint;
    }>;
    getDatasetSize(): Promise<bigint>;
    getFilteredPatients(minAge: bigint, maxAge: bigint, gender: Gender | null, race: Race | null, diabetes: boolean | null, strokeHistory: boolean | null): Promise<Array<Patient>>;
}
import type { ChestPainType as _ChestPainType, Gender as _Gender, Patient as _Patient, Race as _Race, Thalassemia as _Thalassemia } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getConfiguration(): Promise<{
        ageMax: bigint;
        ageMin: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfiguration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfiguration();
            return result;
        }
    }
    async getDatasetSize(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatasetSize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatasetSize();
            return result;
        }
    }
    async getFilteredPatients(arg0: bigint, arg1: bigint, arg2: Gender | null, arg3: Race | null, arg4: boolean | null, arg5: boolean | null): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredPatients(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredPatients(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChestPainType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChestPainType): ChestPainType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Race_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Race): Race {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Thalassemia_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Thalassemia): Thalassemia {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    exerciseInducedAngina: boolean;
    maxHeartRate: bigint;
    chestPain: _ChestPainType;
    majorVessels: bigint;
    race: _Race;
    thal: _Thalassemia;
    restingBP: bigint;
    slope: bigint;
    gender: _Gender;
    stDepression: number;
    heartDisease: boolean;
    strokeHistory: boolean;
    diabetes: boolean;
    fastingBloodSugar: boolean;
    restingECG: bigint;
    cholesterol: bigint;
}): {
    age: bigint;
    exerciseInducedAngina: boolean;
    maxHeartRate: bigint;
    chestPain: ChestPainType;
    majorVessels: bigint;
    race: Race;
    thal: Thalassemia;
    restingBP: bigint;
    slope: bigint;
    gender: Gender;
    stDepression: number;
    heartDisease: boolean;
    strokeHistory: boolean;
    diabetes: boolean;
    fastingBloodSugar: boolean;
    restingECG: bigint;
    cholesterol: bigint;
} {
    return {
        age: value.age,
        exerciseInducedAngina: value.exerciseInducedAngina,
        maxHeartRate: value.maxHeartRate,
        chestPain: from_candid_ChestPainType_n11(_uploadFile, _downloadFile, value.chestPain),
        majorVessels: value.majorVessels,
        race: from_candid_Race_n13(_uploadFile, _downloadFile, value.race),
        thal: from_candid_Thalassemia_n15(_uploadFile, _downloadFile, value.thal),
        restingBP: value.restingBP,
        slope: value.slope,
        gender: from_candid_Gender_n17(_uploadFile, _downloadFile, value.gender),
        stDepression: value.stDepression,
        heartDisease: value.heartDisease,
        strokeHistory: value.strokeHistory,
        diabetes: value.diabetes,
        fastingBloodSugar: value.fastingBloodSugar,
        restingECG: value.restingECG,
        cholesterol: value.cholesterol
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    atypicalAngina: null;
} | {
    typicalAngina: null;
} | {
    asymptomatic: null;
} | {
    nonAnginalPain: null;
}): ChestPainType {
    return "atypicalAngina" in value ? ChestPainType.atypicalAngina : "typicalAngina" in value ? ChestPainType.typicalAngina : "asymptomatic" in value ? ChestPainType.asymptomatic : "nonAnginalPain" in value ? ChestPainType.nonAnginalPain : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    asian: null;
} | {
    other: null;
} | {
    latino: null;
} | {
    black: null;
} | {
    white: null;
}): Race {
    return "asian" in value ? Race.asian : "other" in value ? Race.other : "latino" in value ? Race.latino : "black" in value ? Race.black : "white" in value ? Race.white : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    fixedDefect: null;
} | {
    reversibleDefect: null;
}): Thalassemia {
    return "normal" in value ? Thalassemia.normal : "fixedDefect" in value ? Thalassemia.fixedDefect : "reversibleDefect" in value ? Thalassemia.reversibleDefect : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Race_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Race): _Race {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender | null): [] | [_Gender] {
    return value === null ? candid_none() : candid_some(to_candid_Gender_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Race | null): [] | [_Race] {
    return value === null ? candid_none() : candid_some(to_candid_Race_n5(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Race): {
    asian: null;
} | {
    other: null;
} | {
    latino: null;
} | {
    black: null;
} | {
    white: null;
} {
    return value == Race.asian ? {
        asian: null
    } : value == Race.other ? {
        other: null
    } : value == Race.latino ? {
        latino: null
    } : value == Race.black ? {
        black: null
    } : value == Race.white ? {
        white: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
