/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const Race = IDL.Variant({
  'asian' : IDL.Null,
  'other' : IDL.Null,
  'latino' : IDL.Null,
  'black' : IDL.Null,
  'white' : IDL.Null,
});
export const ChestPainType = IDL.Variant({
  'atypicalAngina' : IDL.Null,
  'typicalAngina' : IDL.Null,
  'asymptomatic' : IDL.Null,
  'nonAnginalPain' : IDL.Null,
});
export const Thalassemia = IDL.Variant({
  'normal' : IDL.Null,
  'fixedDefect' : IDL.Null,
  'reversibleDefect' : IDL.Null,
});
export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'exerciseInducedAngina' : IDL.Bool,
  'maxHeartRate' : IDL.Nat,
  'chestPain' : ChestPainType,
  'majorVessels' : IDL.Nat,
  'race' : Race,
  'thal' : Thalassemia,
  'restingBP' : IDL.Nat,
  'slope' : IDL.Nat,
  'gender' : Gender,
  'stDepression' : IDL.Float64,
  'heartDisease' : IDL.Bool,
  'strokeHistory' : IDL.Bool,
  'diabetes' : IDL.Bool,
  'fastingBloodSugar' : IDL.Bool,
  'restingECG' : IDL.Nat,
  'cholesterol' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getConfiguration' : IDL.Func(
      [],
      [IDL.Record({ 'ageMax' : IDL.Nat, 'ageMin' : IDL.Nat })],
      ['query'],
    ),
  'getDatasetSize' : IDL.Func([], [IDL.Nat], ['query']),
  'getFilteredPatients' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(Gender),
        IDL.Opt(Race),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(Patient)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const Race = IDL.Variant({
    'asian' : IDL.Null,
    'other' : IDL.Null,
    'latino' : IDL.Null,
    'black' : IDL.Null,
    'white' : IDL.Null,
  });
  const ChestPainType = IDL.Variant({
    'atypicalAngina' : IDL.Null,
    'typicalAngina' : IDL.Null,
    'asymptomatic' : IDL.Null,
    'nonAnginalPain' : IDL.Null,
  });
  const Thalassemia = IDL.Variant({
    'normal' : IDL.Null,
    'fixedDefect' : IDL.Null,
    'reversibleDefect' : IDL.Null,
  });
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'exerciseInducedAngina' : IDL.Bool,
    'maxHeartRate' : IDL.Nat,
    'chestPain' : ChestPainType,
    'majorVessels' : IDL.Nat,
    'race' : Race,
    'thal' : Thalassemia,
    'restingBP' : IDL.Nat,
    'slope' : IDL.Nat,
    'gender' : Gender,
    'stDepression' : IDL.Float64,
    'heartDisease' : IDL.Bool,
    'strokeHistory' : IDL.Bool,
    'diabetes' : IDL.Bool,
    'fastingBloodSugar' : IDL.Bool,
    'restingECG' : IDL.Nat,
    'cholesterol' : IDL.Nat,
  });
  
  return IDL.Service({
    'getConfiguration' : IDL.Func(
        [],
        [IDL.Record({ 'ageMax' : IDL.Nat, 'ageMin' : IDL.Nat })],
        ['query'],
      ),
    'getDatasetSize' : IDL.Func([], [IDL.Nat], ['query']),
    'getFilteredPatients' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(Gender),
          IDL.Opt(Race),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(Patient)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };