/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChestPainType = { 'atypicalAngina' : null } |
  { 'typicalAngina' : null } |
  { 'asymptomatic' : null } |
  { 'nonAnginalPain' : null };
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface Patient {
  'age' : bigint,
  'exerciseInducedAngina' : boolean,
  'maxHeartRate' : bigint,
  'chestPain' : ChestPainType,
  'majorVessels' : bigint,
  'race' : Race,
  'thal' : Thalassemia,
  'restingBP' : bigint,
  'slope' : bigint,
  'gender' : Gender,
  'stDepression' : number,
  'heartDisease' : boolean,
  'strokeHistory' : boolean,
  'diabetes' : boolean,
  'fastingBloodSugar' : boolean,
  'restingECG' : bigint,
  'cholesterol' : bigint,
}
export type Race = { 'asian' : null } |
  { 'other' : null } |
  { 'latino' : null } |
  { 'black' : null } |
  { 'white' : null };
export type Thalassemia = { 'normal' : null } |
  { 'fixedDefect' : null } |
  { 'reversibleDefect' : null };
export interface _SERVICE {
  'getConfiguration' : ActorMethod<
    [],
    { 'ageMax' : bigint, 'ageMin' : bigint }
  >,
  'getDatasetSize' : ActorMethod<[], bigint>,
  'getFilteredPatients' : ActorMethod<
    [
      bigint,
      bigint,
      [] | [Gender],
      [] | [Race],
      [] | [boolean],
      [] | [boolean],
    ],
    Array<Patient>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];